services:
    forum.subject.voter:
        class: ForumBundle\Security\SubjectVoter
        tags:
            - { name: security.voter }
    forum.comment.voter:
        class: ForumBundle\Security\CommentVoter
        tags:
            - { name: security.voter }
